releases:
  - name: postgresql
    namespace: storage
    chart: bitnami/postgresql
    version: "15.5.38"
    values:
      - values/postgresql.yaml

  - name: seaweedfs
    namespace: storage
    chart: seaweedfs/seaweedfs
    version: "4.0.1"
    values:
      - values/seaweedfs.yaml
    needs:
      - storage/postgresql