releases:
  - name: kube-prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: "86.1.1"
    values:
      - values/kube-prometheus-stack.yaml

  - name: thanos
    namespace: observability
    chart: bitnami/thanos
    version: "17.5.0"
    values:
      - values/thanos.yaml
#    needs:
#      - observability/kube-prometheus-stack
#      - storage/seaweedfs

  - name: loki
    namespace: observability
    chart: grafana-community/loki
    version: "13.1.2"
    values:
      - values/loki.yaml
#    needs:
#      - storage/seaweedfs

  - name: tempo
    namespace: observability
    chart: grafana-community/tempo-distributed
    version: "1.61.3"
    values:
      - values/tempo.yaml
#    needs:
#      - storage/seaweedfs

  - name: otel-collector
    namespace: observability
    chart: open-telemetry/opentelemetry-collector
    version: "0.115.0"
    values:
      - values/otel-collector.yaml
#    needs:
#      - observability/loki
#      - observability/tempo