releases:
  - name: airflow
    namespace: data-platform
    chart: apache-airflow/airflow
    version: "1.15.0"
    values:
      - values/airflow.yaml
    needs:
      - storage/postgresql

  - name: mlflow
    namespace: data-platform
    chart: community-charts/mlflow
    version: "0.7.19"
    values:
      - values/mlflow.yaml
#    needs:
#      - data-platform/airflow
#      - storage/postgresql