from enum import StrEnum

class TrainModelKeys(StrEnum):
    MODEL_TRAINED_AT_ISO_DATETIME = "MODEL_TRAINED_AT_ISO_DATETIME"
    MLFLOW_RUN_ID = "MLFLOW_RUN_ID"
    MODEL_NAME = "MODEL_NAME"
    MODEL_VERSION = "MODEL_VERSION"
    MODEL_DATASET_MIN_ISO_DATETIME = "MODEL_DATASET_MIN_ISO_DATETIME"
    MODEL_DATASET_MAX_ISO_DATETIME = "MODEL_DATASET_MAX_ISO_DATETIME"
    MODEL_F1_SCORE = "MODEL_F1_SCORE"
    MODEL_PR_AUC = "MODEL_PR_AUC"
    MODEL_RECALL = "MODEL_RECALL"
    MODEL_PRECISION = "MODEL_PRECISION"