from dataclasses import dataclass

@dataclass(frozen=True)
class ModelDeploymentWorkflowsKeys:
    MODEL_DEPLOYMENT_WORKFLOW_ID: str = "MODEL_DEPLOYMENT_WORKFLOW_ID"

@dataclass(frozen=True)
class TrainingPipelineKeys:
    MODEL_TRAINED_AT_ISO_DATETIME: str = "MODEL_TRAINED_AT_ISO_DATETIME"
    MLFLOW_RUN_ID: str = "MLFLOW_RUN_ID"
    MODEL_NAME: str = "MODEL_NAME"
    MODEL_VERSION: str = "MODEL_VERSION"
    MODEL_DATASET_MIN_ISO_DATETIME: str = "MODEL_DATASET_MIN_ISO_DATETIME"
    MODEL_DATASET_MAX_ISO_DATETIME: str = "MODEL_DATASET_MAX_ISO_DATETIME"
    MODEL_METRICS: str = "MODEL_METRICS"