{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "fraud_detection.name" . }}*/}}
{{/*  annotations:*/}}
{{/*    {{- toYaml .Values.podAnnotations | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  replicas: {{ .Values.replicaCount }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: {{ include "fraud_detection.name" . }}*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: {{ include "fraud_detection.name" . }}*/}}
{{/*    spec:*/}}
{{/*      imagePullSecrets:*/}}
{{/*        {{- toYaml .Values.imagePullSecrets | nindent 8 }}*/}}
{{/*      containers:*/}}
{{/*        - name: {{ include "fraud_detection.name" . }}*/}}
{{/*          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"*/}}
{{/*          imagePullPolicy: {{ .Values.image.pullPolicy }}*/}}
{{/*          ports:*/}}
{{/*            - containerPort: {{ .Values.service.port }}*/}}
{{/*          envFrom:*/}}
{{/*            # MLE team credentials (PGUSER, PGPASSWORD, AWS_ACCESS_KEY_ID,*/}}
{{/*            # AWS_SECRET_ACCESS_KEY, SLACK_*, AIRFLOW_*)*/}}
{{/*            - secretRef:*/}}
{{/*                name: {{ .Values.secretName }}*/}}