CREATE TABLE deployed_models (
    model_id                SERIAL              NOT NULL        PRIMARY KEY,
    promoted_at             TIMESTAMPTZ         NOT NULL        DEFAULT NOW(),
    model_name              TEXT                NOT NULL,
    model_version           INT                 NOT NULL,
    dataset_min_date        TIMESTAMPTZ         NULL,
    dataset_max_date        TIMESTAMPTZ         NOT NULL,
    status                  TEXT                NOT NULL        DEFAULT 'active',
    CONSTRAINT deployed_models_name_version_key UNIQUE (model_name, model_version),
    CONSTRAINT status_check CHECK (status IN ('promoting', 'active'))
);

CREATE TABLE pipeline_state (
    pipeline_state_id       INT                 NOT NULL        PRIMARY KEY     DEFAULT 1,
    created_at              TIMESTAMPTZ         NOT NULL        DEFAULT NOW(),
    state                   TEXT                NOT NULL,
    training_approved       BOOLEAN             NOT NULL        DEFAULT FALSE,
    promote_approved        BOOLEAN             NOT NULL        DEFAULT FALSE,
    run_id                  TEXT                NULL,
    model_version           INT                 NULL,
    dataset_min_date        TIMESTAMPTZ         NULL,
    dataset_max_date        TIMESTAMPTZ         NULL,
    drift_slack_ts          TEXT                NOT NULL,
    promote_slack_ts        TEXT                NOT NULL,
--     drift_count             INT                 NOT NULL        DEFAULT 0,
    CONSTRAINT state_check CHECK (state IN ('drift_pending', 'train_pending', 'promoting'))
);

CREATE TABLE transaction_inferences (
    request_id              UUID                NOT NULL        PRIMARY KEY     DEFAULT gen_random_uuid(),
    inference_timestamp     TIMESTAMPTZ         NOT NULL        DEFAULT NOW(),
    transaction_id          UUID                NULL,
    transaction_timestamp   TIMESTAMPTZ         NOT NULL,
    amount                  DOUBLE PRECISION    NOT NULL,
    is_fraud                BOOLEAN             NULL,
    is_fraud_prediction     BOOLEAN             NULL,
    is_fraud_probability    DOUBLE PRECISION    NULL,
    model_deployment_id     INT                 NULL            REFERENCES      deployed_models(model_id),
    v1                      DOUBLE PRECISION    NOT NULL,
    v2                      DOUBLE PRECISION    NOT NULL,
    v3                      DOUBLE PRECISION    NOT NULL,
    v4                      DOUBLE PRECISION    NOT NULL,
    v5                      DOUBLE PRECISION    NOT NULL,
    v6                      DOUBLE PRECISION    NOT NULL,
    v7                      DOUBLE PRECISION    NOT NULL,
    v8                      DOUBLE PRECISION    NOT NULL,
    v9                      DOUBLE PRECISION    NOT NULL,
    v10                     DOUBLE PRECISION    NOT NULL,
    v11                     DOUBLE PRECISION    NOT NULL,
    v12                     DOUBLE PRECISION    NOT NULL,
    v13                     DOUBLE PRECISION    NOT NULL,
    v14                     DOUBLE PRECISION    NOT NULL,
    v15                     DOUBLE PRECISION    NOT NULL,
    v16                     DOUBLE PRECISION    NOT NULL,
    v17                     DOUBLE PRECISION    NOT NULL,
    v18                     DOUBLE PRECISION    NOT NULL,
    v19                     DOUBLE PRECISION    NOT NULL,
    v20                     DOUBLE PRECISION    NOT NULL,
    v21                     DOUBLE PRECISION    NOT NULL,
    v22                     DOUBLE PRECISION    NOT NULL,
    v23                     DOUBLE PRECISION    NOT NULL,
    v24                     DOUBLE PRECISION    NOT NULL,
    v25                     DOUBLE PRECISION    NOT NULL,
    v26                     DOUBLE PRECISION    NOT NULL,
    v27                     DOUBLE PRECISION    NOT NULL,
    v28                     DOUBLE PRECISION    NOT NULL,
    CONSTRAINT transaction_inferences_is_fraud_probability_check CHECK (is_fraud_probability BETWEEN 0 AND 1)
);