from dataclasses import dataclass

@dataclass(frozen=True)
class DriftCheckKeys:
    DRIFT_DETECTED: str = "DRIFT_DETECTED"
    DRIFT_SUMMARY: str = "DRIFT_SUMMARY"

@dataclass(frozen=True)
class ModelDeploymentSuccessionKeys:
    EXPIRED_PROMOTION_APPROVAL_SLACK_TS: str = "EXPIRED_PROMOTION_APPROVAL_SLACK_TS"
    EXPIRED_ID: str = "EXPIRED_ID"
    EXPIRED_MLFLOW_RUN_ID: str = "EXPIRED_MLFLOW_RUN_ID"
    EXPIRED_MODEL_NAME: str = "EXPIRED_MODEL_NAME"
    EXPIRED_MODEL_VERSION: str = "EXPIRED_MODEL_VERSION"
    REPLACEMENT_MODEL_NAME: str = "REPLACEMENT_MODEL_NAME"
    REPLACEMENT_MODEL_VERSION: str = "REPLACEMENT_MODEL_VERSION"