from enum import StrEnum

class DriftCheckKeys(StrEnum):
    DRIFT_DETECTED = "DRIFT_DETECTED"
    DRIFT_SUMMARY = "DRIFT_SUMMARY"
    ACTIVE_MODEL_DEPLOYMENT_MLFLOW_RUN_ID = "ACTIVE_MODEL_DEPLOYMENT_MLFLOW_RUN_ID"

class ExpiredModelDeploymentWorkflowsKeys(StrEnum):
    PROMOTION_APPROVAL_SLACK_TS = "EXPIRED_PROMOTION_APPROVAL_SLACK_TS"
    WORKFLOW_ID = "EXPIRED_WORKFLOW_ID"
    MLFLOW_RUN_ID = "EXPIRED_MLFLOW_RUN_ID"
    MODEL_NAME = "EXPIRED_MODEL_NAME"
    MODEL_VERSION = "EXPIRED_MODEL_VERSION"

class ReservedModelDeploymentWorkflowsKeys(StrEnum):
    MODEL_NAME = "RESERVED_MODEL_NAME"
    MODEL_VERSION = "RESERVED_MODEL_VERSION"