from sqlalchemy import Column, func, DateTime, Float, Boolean
from sqlalchemy.dialects.postgresql import UUID

from services.shared.modules.schemas.postgres.postgres import PostgresTableBase

class TransactionInferences(PostgresTableBase):
    __tablename__ = "transaction_inferences"

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    transaction_id = Column(UUID(as_uuid=True), nullable=True)
    transaction_timestamp = Column(DateTime(timezone=True), nullable=False)
    amount = Column(Float, nullable=False)
    is_fraud = Column(Boolean, nullable=True)
    is_fraud_prediction = Column(Boolean, nullable=True)
    is_fraud_probability = Column(Float, nullable=True)
    model_deployment_id = Column(UUID(as_uuid=True), nullable=True)
    v1 = Column(Float, nullable=False)
    v2 = Column(Float, nullable=False)
    v3 = Column(Float, nullable=False)
    v4 = Column(Float, nullable=False)
    v5 = Column(Float, nullable=False)
    v6 = Column(Float, nullable=False)
    v7 = Column(Float, nullable=False)
    v8 = Column(Float, nullable=False)
    v9 = Column(Float, nullable=False)
    v10 = Column(Float, nullable=False)
    v11 = Column(Float, nullable=False)
    v12 = Column(Float, nullable=False)
    v13 = Column(Float, nullable=False)
    v14 = Column(Float, nullable=False)
    v15 = Column(Float, nullable=False)
    v16 = Column(Float, nullable=False)
    v17 = Column(Float, nullable=False)
    v18 = Column(Float, nullable=False)
    v19 = Column(Float, nullable=False)
    v20 = Column(Float, nullable=False)
    v21 = Column(Float, nullable=False)
    v22 = Column(Float, nullable=False)
    v23 = Column(Float, nullable=False)
    v24 = Column(Float, nullable=False)
    v25 = Column(Float, nullable=False)
    v26 = Column(Float, nullable=False)
    v27 = Column(Float, nullable=False)
    v28 = Column(Float, nullable=False)