ingressClass:
  enabled: false # assure conflict avoidance with k3s built-in Traefik v2

accessLog:
  enabled: true

# ports:
# [dynamic]: # Localhost entrypoint
#   port: [dynamic]

deployment:
  replicas: 1

service:
  type: LoadBalancer
# spec:
#   loadBalancerIP: [dynamic] # K3s container IP
# annotations:
#   "metallb.io/address-pool": [dynamic]