# docker compose up -d --wait
services:
  ministack:
    image: ministackorg/ministack
    container_name: ministack
    networks:
      - ministack_network
    ports:
      - "4566:4566"
    environment:
      DOCKER_NETWORK: ministack_network
      PERSIST_STATE: 1
      LOCALSTACK_PERSISTENCE: 1
      S3_PERSIST: 1
      RDS_PERSIST: 1
      MWAA_PERSIST: 1
      DSQL_PERSIST: 1
      DSQL_STRICT: 1
      LOG_LEVEL: DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "from urllib.request import urlopen; urlopen('http://localhost:4566/_ministack/health')"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  ministack_network:
    name: ministack_network
