[project]
name = "fraud-detection"
version = "0.1.0"
requires-python = "==3.12.13"

[dependency-groups]
mlflow = [
    "boto3>=1.43.14",
    "mlflow>=3.12.0",
    "psycopg2-binary>=2.9.12",
]
fraud_api = [
    "fastapi>=0.136.1",
    "mlflow>=3.12.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.42.1",
    "opentelemetry-instrumentation-fastapi>=0.63b1",
    "opentelemetry-instrumentation-sqlalchemy>=0.63b1",
    "opentelemetry-sdk>=1.42.1",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "python-json-logger>=4.1.0",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.47.0",
    # Dev
    "slack-bolt>=1.28.0",
]
drift_monitor = [
    "boto3>=1.43.14",
    "boto3-stubs[s3]>=1.43.15",
    "evidently>=0.7.21",
    "opentelemetry-exporter-otlp-proto-grpc>=1.42.1",
    "opentelemetry-instrumentation-botocore>=0.63b1",
    "opentelemetry-instrumentation-sqlalchemy>=0.63b1",
    "opentelemetry-sdk>=1.42.1",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=23.0.1",
    "python-json-logger>=4.1.0",
    "slack-sdk>=3.42.0",
    "sqlalchemy>=2.0.49",
]
training_pipeline = [
    "boto3>=1.43.14",
    "imbalanced-learn>=0.14.1",
    "mlflow>=3.12.0",
    "numpy>=2.4.5",
    "opentelemetry-exporter-otlp-proto-grpc>=1.42.1",
    "opentelemetry-instrumentation-botocore>=0.63b1",
    "opentelemetry-instrumentation-sqlalchemy>=0.63b1",
    "opentelemetry-sdk>=1.42.1",
    "optuna>=4.8.0",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=23.0.1",
    "python-json-logger>=4.1.0",
    "scikit-learn>=1.8.0",
    "slack-sdk>=3.42.0",
    "sqlalchemy>=2.0.49",
    "xgboost>=3.2.0",
]
archiving = [
    "boto3>=1.43.14",
    "opentelemetry-exporter-otlp-proto-grpc>=1.42.1",
    "opentelemetry-instrumentation-botocore>=0.63b1",
    "opentelemetry-instrumentation-sqlalchemy>=0.63b1",
    "opentelemetry-sdk>=1.42.1",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=23.0.1",
    "python-json-logger>=4.1.0",
    "sqlalchemy>=2.0.49",
]
dev = [
    "boto3-stubs>=1.43.15",
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "kaleido>=0.2.1",
    "locust>=2.44.0",
    "matplotlib>=3.10.9",
    "moto[s3]>=5.2.1",
    "mypy>=2.1.0",
    "nbformat>=5.10.4",
    "numba>=0.61.0",
    "numpy>=2.4.5",
    "pandas-stubs>=3.0.0.260204",
    "plotly>=5.24.1",
    "pre-commit>=4.6.0",
    "psycopg2-binary>=2.9.12",
    "pytest>=9.0.3",
    "pytest-env>=1.6.0",
    "pytest-mock>=3.15.1",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "ruff>=0.15.13",
    "seaborn>=0.13.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
env = [
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
