auth_enabled: false
server:
  http_listen_port: ${LOKI_HTTP_PORT}
  grpc_listen_port: ${LOKI_GRPC_PORT}
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  aws:
    s3: http://${SEAWEEDFS_ACCESS_KEY}:${SEAWEEDFS_SECRET_KEY}@${SEAWEEDFS_HOST}:${SEAWEEDFS_S3_PORT}/${SEAWEEDFS_LOKI_CHUNKS_BUCKET}
    s3forcepathstyle: true
    insecure: true
    bucketnames: ${SEAWEEDFS_LOKI_CHUNKS_BUCKET}
    region: us-east-1
ruler:
  storage:
    type: s3
    s3:
      bucketnames: ${SEAWEEDFS_LOKI_RULES_BUCKET}
      region: us-east-1
      s3forcepathstyle: true
      insecure: true
      endpoint: ${SEAWEEDFS_S3_URL}
      access_key_id: ${SEAWEEDFS_ACCESS_KEY}
      secret_access_key: ${SEAWEEDFS_SECRET_KEY}
limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  otlp_config:
    default_labels_enabled:
      exporter: false
      job: true
compactor:
  working_directory: /loki/compactor
  shared_store: s3
