from services.fraud_api.src.modules.schemas.fraud_classification_inference import FraudClassificationRequest, FraudClassificationOutput
from services.fraud_api.src.modules.schemas.health import HealthResponse
from services.fraud_api.src.modules.schemas.mlflow import DeployedModel