\getenv FRAUD_DETECTION_DB_NAME FRAUD_DETECTION_DB_NAME
SELECT 'CREATE DATABASE :"FRAUD_DETECTION_DB_NAME"'
WHERE NOT EXISTS (
    SELECT FROM pg_database
    WHERE datname = :'FRAUD_DETECTION_DB_NAME'
)\gexec

\getenv MLFLOW_DB_NAME MLFLOW_DB_NAME
SELECT 'CREATE DATABASE :"MLFLOW_DB_NAME"'
WHERE NOT EXISTS (
    SELECT FROM pg_database
    WHERE datname = :'MLFLOW_DB_NAME'
)\gexec

\getenv GRAFANA_DB_NAME GRAFANA_DB_NAME
SELECT 'CREATE DATABASE :"GRAFANA_DB_NAME"'
WHERE NOT EXISTS (
    SELECT FROM pg_database
    WHERE datname = :'GRAFANA_DB_NAME'
)\gexec