from dataclasses import dataclass

@dataclass(frozen=True)
class TrainModelKeys:
    MODEL_TRAINED_AT_ISO_DATETIME: str = "MODEL_TRAINED_AT_ISO_DATETIME"
    MLFLOW_RUN_ID: str = "MLFLOW_RUN_ID"
    MODEL_NAME: str = "MODEL_NAME"
    MODEL_VERSION: str = "MODEL_VERSION"
    MODEL_DATASET_MIN_ISO_DATETIME: str = "MODEL_DATASET_MIN_ISO_DATETIME"
    MODEL_DATASET_MAX_ISO_DATETIME: str = "MODEL_DATASET_MAX_ISO_DATETIME"
    MODEL_F1_SCORE: str = "MODEL_F1_SCORE"
    MODEL_PR_AUC: str = "MODEL_PR_AUC"
    MODEL_RECALL: str = "MODEL_RECALL"
    MODEL_PRECISION: str = "MODEL_PRECISION"