apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: observability
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: thanos-data
      endpoint: seaweedfs-filer.storage.svc.cluster.local:8333
      access_key: local-access-key
      secret_key: fraud_detection
      insecure: true
      signature_version2: false