from enum import Enum

class ModelDeploymentWorkflowsKeys(str, Enum):
    MODEL_DEPLOYMENT_WORKFLOW_ID_KEY = "MODEL_DEPLOYMENT_WORKFLOW_ID"
    TRAINING_APPROVAL_SLACK_TS_KEY = "TRAINING_APPROVAL_SLACK_TS"

class ModelDeploymentSuccessionKeys(str, Enum):
    EXPIRED_MLFLOW_RUN_ID_KEY = "EXPIRED_MLFLOW_RUN_ID"
    EXPIRED_MODEL_NAME = "EXPIRED_MODEL_NAME"
    EXPIRED_MODEL_VERSION = "EXPIRED_MODEL_VERSION"
    REPLACEMENT_MODEL_NAME = "REPLACEMENT_MODEL_NAME"
    REPLACEMENT_MODEL_VERSION = "REPLACEMENT_MODEL_VERSION"