from enum import StrEnum

class ModelDeploymentKeys(StrEnum):
    MODEL_DEPLOYMENT_ID = "MODEL_DEPLOYMENT_ID"
    MODEL_DEPLOYMENT_MLFLOW_RUN_ID = "MODEL_DEPLOYMENT_MLFLOW_RUN_ID"

class ModelDeploymentWorkflowsKeys(StrEnum):
    MODEL_DEPLOYMENT_WORKFLOW_ID = "MODEL_DEPLOYMENT_WORKFLOW_ID"
    SLACK_TRAINING_APPROVAL_MESSAGE_TS = "SLACK_TRAINING_APPROVAL_MESSAGE_TS"
    TRAIN_MODEL_FOR_PROMOTION = "TRAIN_MODEL_FOR_PROMOTION"
    SLACK_PROMOTION_APPROVAL_MESSAGE_TS = "SLACK_PROMOTION_APPROVAL_MESSAGE_TS"