backendStore:
  databaseMigration: true
  postgres:
    enabled: true
#   host: [dynamic]
#   port: [dynamic]
#   database: [dynamic]
#   user: [dynamic]
#   password: [dynamic]

artifactRoot:
  s3:
    enabled: true
    path: "artifacts"
#   awsAccessKeyId: [dynamic]
#   awsSecretAccessKey: [dynamic]
#   bucket: [dynamic]
  proxiedArtifactStorage: true # Changes destination host from s3 to mlflow

extraFlags:
  - serveArtifacts # Enables mlflow to proxy artifact connection from s3 (uploads/downloads)

extraEnvVars:
  MLFLOW_ENABLE_WORKSPACES: true
#   SCRIPT_NAME: [dynamic] # Aligns request calls with path prefixed host from reverse proxy (traefik)
#   MLFLOW_S3_ENDPOINT_URL: [dynamic]
#   AWS_DEFAULT_REGION: [dynamic]

auth:
  enabled: true
  defaultPermission: MANAGE
  postgres:
    enabled: true
#   host: [dynamic]
#   port: [dynamic]
#   database: [dynamic]
#   user: [dynamic]
#   password: [dynamic]

# flaskServerSecretKey: [dynamic] # Avoids unexpected logout

service:
  type: ClusterIP # Internal access only
# port: [dynamic] # service port (HTTP)
# containerPort: [dynamic] # targetPort and containerPort

# fullnameOverride: [dynamic] # Sets hostname