from enum import StrEnum

class DriftCheckKeys(StrEnum):
    DRIFT_DETECTED = "DRIFT_DETECTED"
    DRIFT_SUMMARY = "DRIFT_SUMMARY"
    # ACTIVE_MODEL_DEPLOYMENT_MLFLOW_RUN_ID = "ACTIVE_MODEL_DEPLOYMENT_MLFLOW_RUN_ID"