apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: $THANOS_QUERY_URL
    access: proxy
    isDefault:
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
          urlDisplayLabel: View in Tempo
