apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    url: $TEMPO_URL
    access: proxy
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true