stream_over_http_enabled: true
server:
  http_listen_port: ${TEMPO_PORT}
  log_level: info
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:${OTEL_GRPC_PORT}
        http:
          endpoint: 0.0.0.0:${OTEL_HTTP_PORT}
ingester:
  max_block_duration: 5m
compactor:
  compaction:
    block_retention: 1h
storage:
  trace:
    backend: s3
    s3:
      endpoint: ${SEAWEEDFS_S3_URL}
      bucket: ${SEAWEEDFS_TEMPO_TRACES_BUCKET}
      access_key: ${SEAWEEDFS_ACCESS_KEY_PATH}
      secret_key: ${SEAWEEDFS_SECRET_KEY_PATH}
      forcepathstyle: true
      insecure: true
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]