from enum import Enum

class TrainingPipelineKeys(str, Enum):
    MODEL_TRAINED_AT_ISO_DATETIME_KEY = "MODEL_TRAINED_AT_ISO_DATETIME"
    MLFLOW_RUN_ID_KEY = "MLFLOW_RUN_ID"
    MODEL_NAME_KEY = "MODEL_NAME"
    MODEL_VERSION_KEY = "MODEL_VERSION"
    MODEL_DATASET_MIN_ISO_DATETIME_KEY = "MODEL_DATASET_MIN_ISO_DATETIME"
    MODEL_DATASET_MAX_ISO_DATETIME_KEY = "MODEL_DATASET_MAX_ISO_DATETIME"
    MODEL_METRICS_KEY = "MODEL_METRICS"